# Generated by Django 4.0.3 on 2022-03-28 16:22

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=13, null=True, unique=True,
                                   validators=[users.models.validate_phone_number]),
        ),
    ]
