# Generated by Django 4.0.3 on 2022-03-28 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('location', models.CharField(blank=True, max_length=50)),
                ('description', models.TextField(blank=True)),
                ('date_time_start', models.DateTimeField(blank=True, null=True)),
                ('date_time_end', models.DateTimeField(blank=True, null=True)),
                ('color', models.CharField(choices=[('#FF0000', 'Red'), ('#FFC0CB', 'Pink'), ('#FFA500', 'Orange'), ('#FFFF00', 'Yellow'), ('#800080', 'Purple'), ('#008000', 'Green'), ('#0000FF', 'Blue'), ('#A52A2A', 'Brown'), ('#FFFFFF', 'White'), ('#808080', 'Gray'), ('#000000', 'Black')], default='#000000', max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='EventParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_creator', models.BooleanField(default=False)),
                ('event_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.event')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PossibleMeeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time_start', models.DateTimeField()),
                ('date_time_end', models.DateTimeField()),
                ('participant_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                 to='events.eventparticipant')),
            ],
        ),
        migrations.AddField(
            model_name='eventparticipant',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.user'),
        ),
    ]
