# Generated by Django 4.0.3 on 2022-03-31 21:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_add_event_participant_test_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='PossibleMeeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time_start', models.DateTimeField()),
                ('date_time_end', models.DateTimeField()),
                ('participant_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                 to='events.eventparticipant')),
            ],
        ),
    ]
