# Generated by Django 4.0.3 on 2022-04-12 22:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_add_possible_meeting_test_data'),
        ('eventfiles', '0002_add_events_files_test_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventfile',
            name='participant_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='events.eventparticipant'),
        ),
    ]
