# Generated by Django 4.0.3 on 2022-04-11 10:26

import django.db.models.functions.datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import reminders.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0006_add_possible_meeting_test_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(blank=True, null=True, validators=[reminders.models.validate_date])),
                ('messages', models.TextField(blank=True, null=True)),
                ('method', models.CharField(
                    choices=[('web', 'Website'), ('ema', 'Email'), ('wae', 'Website and Email')],
                    default='web', max_length=3)
                 ),
                ('participant_id', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='events.eventparticipant')
                 ),
            ],
        ),
        migrations.AddConstraint(
            model_name='reminder',
            constraint=models.UniqueConstraint(fields=('participant_id', 'date_time'), name='unique reminder'),
        ),
        migrations.AddConstraint(
            model_name='reminder',
            constraint=models.CheckConstraint(
                check=models.Q(('date_time__gte', django.db.models.functions.datetime.Now())),
                name='date_time__gte_current_time'
            ),
        ),
    ]
