# Generated by Django 4.0.3 on 2022-04-28 09:20

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.functions.datetime
import django.utils.timezone
import reminders.class_models.reminder_models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0003_eventparticipant'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(
                    default=django.utils.timezone.now,
                    validators=[reminders.class_models.reminder_models.validate_date]
                    )
                 ),
                ('messages', models.TextField(blank=True, null=True)),
                ('method', models.CharField(
                    choices=[('web', 'Website'), ('ema', 'Email'), ('wae', 'Website and Email')],
                    default='web', max_length=3
                    )
                 ),
                ('participant_id', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='events.eventparticipant')
                 ),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seen_time', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('sent_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('message', models.TextField(blank=True, null=True)),
                ('participant_id', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    to='events.eventparticipant'
                    )
                 ),
            ],
        ),
        migrations.AddConstraint(
            model_name='reminder',
            constraint=models.UniqueConstraint(
                fields=('participant_id', 'date_time', 'messages'),
                name='unique reminder'
            ),
        ),
        migrations.AddConstraint(
            model_name='notification',
            constraint=models.UniqueConstraint(fields=('participant_id', 'sent_time'), name='unique notification'),
        ),
        migrations.AddConstraint(
            model_name='notification',
            constraint=models.CheckConstraint(
                check=models.Q(('sent_time__gte', django.db.models.functions.datetime.Now())),
                name='sent_time__gte_current_time'
             ),
        ),
    ]
