# Generated by Django 4.0.3 on 2022-04-18 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminders', '0002_add_reminder_test_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reminder',
            name='method',
            field=models.CharField(choices=[('ema', 'Email'), ('web', 'Website'), ('wae', 'Website and Email')], default='web', max_length=3),
        ),
    ]
