# Generated by Django 4.0.3 on 2022-04-10 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reminders', '0002_add_reminder_test_data'),
        ('reminders', '0003_add_notification_test_data'),
    ]

    operations = [
    ]
