# Generated by Django 4.0.4 on 2022-05-12 20:49

from django.db import migrations


def add_google_account(apps, schema_editor):
    import environ
    from allauth.socialaccount.models import SocialApp

    env = environ.Env()
    environ.Env.read_env()

    app = SocialApp(provider='google', name='OAuth-App', client_id=env("AUTH_ID"), secret=env("AUTH_SECRET"))
    app.save()
    app.sites.set('1')


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_update_site_name'),
        ('socialaccount', '0003_extra_data_default_dict'),
    ]

    operations = [
        migrations.RunPython(add_google_account, migrations.RunPython.noop),
    ]
